# Generated by Django 2.0.7 on 2018-07-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slog', models.CharField(blank=True, max_length=50, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('num_on_page', models.IntegerField(blank=True, null=True)),
                ('glas', models.IntegerField(blank=True, null=True)),
                ('feature', models.IntegerField(blank=True, choices=[(0, 'Обычный символ'), (1, 'Первый символ на странице'), (2, 'Первый символ в строке'), (3, 'Последний символ в строке'), (4, 'Последний символ на странице'), (5, 'Нераспознанный, Обычный'), (6, 'Нераспознанный, Первый символ на странице'), (7, 'Нераспознанный, Первый символ в строке'), (8, 'Нераспознанный, Последний символ в строке'), (9, 'Нераспознанный, Последний символ на странице')], default=0, null=True)),
                ('pometa', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Нота в песнопении',
                'verbose_name_plural': 'Ноты в песнопении',
            },
        ),
        migrations.CreateModel(
            name='signs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=11)),
                ('ID_sign', models.CharField(max_length=11)),
                ('grp', models.CharField(max_length=10)),
                ('signID', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Знамя',
                'verbose_name_plural': 'Знамена',
                'db_table': 'signs',
            },
        ),
        migrations.AddField(
            model_name='chants',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chants.signs'),
        ),
    ]
